### ISSUE TITLE
Broken Pipe Error

### ISSUE THREAD

**Issue by madiltalay** [RameshArvind/Pytorch-Matching-Networks#1]
System:
Windows 10, Cuda Toolkit 9.0, GPU = Geforce GTX 750 Ti

Problem:
In the main training loop,
 for iteration, (support_images, support_labels, images, labels) in enumerate(train_dataset_loader):
     26     # Move our data to GPU
     27     support_batch_torch = support_images.to(device)

Gives: BrokenPipeError: [Errno 32] Broken pipe

Any help would be much appreciated.

**Comment by madiltalay** [comment]
I don't know what changed, but now it is running without errors.
Thanks for the wonderful tutorial.

**Comment by RameshArvind** [comment]
I'm happy to hear that. I wanted to get back to you earlier. Sorry about that. As for the cause of the error from before. There's a chance the training might've been interrupted mid-way causing the GPU memory to be in an inconsistent state. To my knowledge the only way to resolve this issue is to clear it and restart your experiment. You can do so by following the steps listed [here](https://forums.fast.ai/t/ipyexperiments-getting-the-most-out-of-your-gpu-ram-in-jupyter-notebook/30145). Alternatively on google colab you may just restart the runtime to fix the issue.
